### PR TITLE
feat: inspect fixtures

### PR DESCRIPTION
**Pull request by floredelasteyrie**

### CODE REVIEW

**Comment by d-tw** [comment]
Have a look at #177 - there are no more makefiles 😎

**Comment by floredelasteyrie** [comment]
@d-tw Seems to be incompatible with the latest updates on devkit (I think it comes from some fixtures in Syrupy)
Error is: `TypeError: unsupported operand type(s) for |: 'list' and 'int'`

Maybe better to close this PR for now

**Comment by d-tw** [comment]
@floredelasteyrie even when you rebase?

**Comment by floredelasteyrie** [comment]
@d-tw Yes - I pulled locally to update my PR and it's no longer working

**Pull request closed without merging**
